services:
  builder:
    amazeeio:
      type: none
      push: false
  cli:
    amazeeio:
      type: none
  nginx:
    amazeeio:
      type: nginx-php
  php:
    amazeeio:
      type: nginx-php
  mariadb:
    amazeeio:
      type: mariadb

tasks:
  post_deploy:
    - cd web && drush -y si
    - cd web && drush -y status